[env:esp32s3devkitc]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    # LED控制
    FastLED/FastLED@^3.6.0
    # FFT音频分析
    kosme/ArduinoFFT@^1.6.0
    # HTTP客户端
    https://github.com/tzapu/WiFiManager.git
    # JSON解析
    bblanchon/ArduinoJson@^7.0.4
    # NVS存储
